server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customer_db
    username: allan
    password: dev

  flyway:
    url: jdbc:mysql://127.0.0.1:3306/customer_db
    user: allan
    password: dev

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: none

    open-in-view: true

  profiles:
    active: dev